steps:
- name: node:14-alpine
  entrypoint: npm
  args: ['install']

- name: node:14-alpine
  entrypoint: npm
  args: ['run', 'lint']

- name: node:14-alpine
  entrypoint: npm
  args: ['run', 'test:coverage']

- name: node:14-alpine
  entrypoint: npm
  args: ['run', 'build']

- name: gcr.io/${PROJECT_ID}/firebase
  args: ['deploy', '--project=${PROJECT_ID}', '--only=hosting']